# Generated by Django 4.0 on 2021-12-28 14:01

from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('raw_file_path', models.FilePathField(path=pathlib.PurePosixPath('/Users/pedroalves/projects/Lusofona/TFCs/app4shm_django_server/app4shm/app4shm/raw_files'))),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='core.structure')),
            ],
        ),
    ]
