# Generated by Django 4.0 on 2022-01-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='raw_file_path',
        ),
        migrations.AddField(
            model_name='reading',
            name='raw_file',
            field=models.FileField(null=True, upload_to='raw_readings'),
        ),
    ]
