# Generated by Django 4.0 on 2022-01-21 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_reading_raw_file_path_reading_raw_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelchFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welch_frequencies', to='core.reading')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='welch_frequencies', to='core.structure')),
            ],
        ),
    ]
