# Generated by Django 4.0 on 2022-02-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_naturalfrequencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSpectrum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('raw_file', models.FileField(null=True, upload_to='raw_readings')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_series', to='core.structure')),
            ],
        ),
        migrations.RemoveField(
            model_name='reading',
            name='structure',
        ),
        migrations.DeleteModel(
            name='WelchFrequency',
        ),
        migrations.AddField(
            model_name='powerspectrum',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_spectrum', to='core.timeseries'),
        ),
        migrations.AddField(
            model_name='powerspectrum',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_spectrum', to='core.structure'),
        ),
        migrations.AlterField(
            model_name='naturalfrequencies',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='natural_frequencies', to='core.timeseries'),
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
    ]
