# Generated by Django 4.0 on 2022-02-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_powerspectrum_timeseries_remove_reading_structure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerspectrum',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='powerspectrum',
            name='x',
        ),
        migrations.RemoveField(
            model_name='powerspectrum',
            name='y',
        ),
        migrations.RemoveField(
            model_name='powerspectrum',
            name='z',
        ),
        migrations.AddField(
            model_name='powerspectrum',
            name='raw_file',
            field=models.FileField(null=True, upload_to='raw_power_spectrum'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='raw_file',
            field=models.FileField(null=True, upload_to='raw_time_series'),
        ),
    ]
