# Generated by Django 4.0 on 2022-10-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_powerspectrum_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naturalfrequencies',
            options={'verbose_name_plural': 'Natural frequencies'},
        ),
        migrations.AlterModelOptions(
            name='timeseries',
            options={'verbose_name_plural': 'Time series'},
        ),
        migrations.AddField(
            model_name='naturalfrequencies',
            name='testing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
