# Generated by Django 4.0 on 2022-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_naturalfrequencies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
