# Generated by Django 4.0 on 2022-07-31 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_alter_structure_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructurePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission', to='core.structure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
