# Generated by Django 4.0 on 2022-12-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_structurepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naturalfrequencies',
            old_name='testing',
            new_name='training',
        ),
    ]
