# Generated by Django 4.0 on 2023-09-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_naturalfrequencies_owner_powerspectrum_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerspectrum',
            name='owner',
        ),
    ]
