# Generated by Django 5.1.2 on 2025-02-21 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_powerspectrum_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='cable_length',
            field=models.FloatField(blank=True, default=0.0, help_text='(meters)', null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='cable_mass',
            field=models.FloatField(blank=True, default=0.0, help_text='(kilograms/meters)', null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='structure_type',
            field=models.CharField(choices=[('structure', 'Structure'), ('cable', 'Cable')], default='structure', max_length=10),
        ),
        migrations.CreateModel(
            name='CableForce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencies', models.JSONField()),
                ('mean_force', models.IntegerField()),
                ('force_freq1', models.IntegerField()),
                ('force_freq2', models.IntegerField()),
                ('force_freq3', models.IntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cable_force', to='core.timeseries')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cable_force', to='core.structure')),
            ],
            options={
                'verbose_name_plural': 'Cable forces',
            },
        ),
    ]
