# Generated by Django 5.1.2 on 2025-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_structure_cable_length_structure_cable_mass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cableforce',
            name='force_freq1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cableforce',
            name='force_freq2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cableforce',
            name='force_freq3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cableforce',
            name='mean_force',
            field=models.IntegerField(default=0),
        ),
    ]
