# Generated by Django 5.1.2 on 2025-02-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cableforce_force_freq1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cableforce',
            old_name='mean_force',
            new_name='cable_force',
        ),
    ]
