# Generated by Django 5.1.2 on 2025-03-13 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_mean_force_cableforce_cable_force'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('master', models.BooleanField(null=True)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network', to='core.structure')),
            ],
        ),
        migrations.CreateModel(
            name='StructurePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(default=0, help_text='(meters)')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structure_position', to='core.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position', to='core.network')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position', to='core.timeseries')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('structure_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position', to='core.structureposition')),
            ],
        ),
    ]
