# Generated by Django 5.1.2 on 2025-03-13 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_network_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='position', to='core.timeseries'),
        ),
    ]
