# Generated by Django 5.1.2 on 2025-03-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_position_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('reading', 'reading'), ('completed', 'completed')], default='waiting', max_length=10),
        ),
    ]
